name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Droplet
      env:
        SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
      run: |
        # Create a temporary SSH key file
        echo "$SSH_KEY" > temp_key
        chmod 600 temp_key

        # Copy the build files to the server
        scp -i temp_key -r ./build/* root@134.209.157.190:/var/www/react-app/

        # Restart Nginx on the server
        ssh -i temp_key root@134.209.157.190 "sudo systemctl restart nginx"

        # Clean up
        rm temp_key