name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 134.209.157.190
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          rm -rf /var/www/react-app/*
          mkdir -p /var/www/react-app
          scp -r ./build/* root@134.209.157.190:/var/www/react-app/
          sudo systemctl restart nginx