name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install
        npm run build

    - name: Deploy to DigitalOcean
      run: |
        ssh root@143.244.142.38
        cd /react-app-droplet &&
        git pull &&
        npm install &&
        npm run build &&
        pm2 restart all
        "
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}